In [5]:
#jam3 dyal matrice m3a matrice
import numpy as np

A = np.array([[4, 8], [3, 7]])
B = np.array([[1, 0], [5, 2]])
A+B

array([[5, 8],
       [8, 9]])

In [4]:
#tar7 dyal matrice m3a matrice
C = np.array([[1, 2], [3, 4]])
D = np.array([[5, 6], [7, 8]])
C-D

array([[-4, -4],
       [-4, -4]])

In [6]:
#darb dyal matrice m3a raqem
E = np.array([[1, 2], [3, 4]])
E*2

array([[2, 4],
       [6, 8]])

In [7]:
#9isma dyal matrice m3a raqem
F = np.array([[1, 2], [3, 4]])
F/2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [8]:
#derb dyal matrice x vector
matrice = np.array([[1, 2], [3, 4], [7,9]])
vecteur = np.array([1, 2])
np.dot(matrice, vecteur)

array([ 5, 11, 25])

In [10]:
#bach nqelbo wahed matrice
A = np.array([[1, 2], [3, 4], [7, 9]])
T = np.transpose(A)
A,T

(array([[1, 2],
        [3, 4],
        [7, 9]]),
 array([[1, 3, 7],
        [2, 4, 9]]))

In [11]:
#bach n printiw colons w lignes dyal matrice
print(format(A.shape))
print(format(T.shape))

(3, 2)
(2, 3)


In [12]:
#bach ndiro inverse l matrice w net2ekdo anaha shiha
from numpy.linalg import inv
N = np.array([[1, 2], [3, 4]])
I = inv(N)
R = np.dot(N, I)
np.allclose(R, np.eye(2))

True

In [13]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [14]:
print(N.shape)
print(np.linalg.det(N))

(2, 2)
-2.0000000000000004


In [18]:
import cv2

# Chemin de l'image
image_path = 'C:\\Users\\xdweb\\OneDrive\\Documents\\IA-CMC\\@xDweb\\0x01 My Designe\\your_image.jpg'


# Lire l'image
image = cv2.imread(image_path)

# Vérifier si l'image a été correctement lue
if image is not None:
    print("L'image a été chargée avec succès.")
    # Afficher l'image
    cv2.imshow("Image", image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
else:
    print("Impossible de charger l'image.")


Impossible de charger l'image.
